---
controller:
  ingressClassResource:
    default: false

  config:
    enable-real-ip: true
    use-forwarded-headers: true

  service:
    externalTrafficPolicy: "Cluster"
    annotations:
      metallb.universe.tf/address-pool: "private-ip"
