---
controller:
  ingressClassResource:
    default: false

  config:
    enable-real-ip: true
    use-forwarded-headers: true
    proxy-body-size: 0

  service:
    externalTrafficPolicy: "Local"
    annotations:
      metallb.universe.tf/address-pool: "private-ip"
