apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 1h
  chart:
    spec:
      version: 1.0.0
      chart: meta-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
      interval: 1h

  install:
    crds: Create
  upgrade:
    crds: CreateReplace

  values:
    namespacesToMonitor:
      - loki

    clusterLabelValue: "home"

    cloud:
      logs:
        enabled: false
      metrics:
        enabled: false
      traces:

    local:
      grafana:
        enabled: true
      logs:
        enabled: true
      metrics:
        enabled: true
      traces:
        enabled: true
      minio:
        enabled: true

    grafana:
      ingress:
        enabled: true
        ingressClassName: "nginx"

        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/hostname: "grafana.psalkowski.pl"

        hosts:
          - host: grafana.psalkowski.pl
            paths:
              - path: /
                pathType: Prefix

        tls:
          - secretName: grafana.psalkowski.pl-tls
            hosts:
              - grafana.psalkowski.pl

    loki:
      monitoring:
        dashboards:
          enabled: true
        rules:
          enabled: true
