# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secretName postgres
spec:
  refreshInterval: 5m
  target:
    name: *secretName
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        POSTGRES_PASSWORD: |-
          {{ .password }}

  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: cd09a649-515d-4ab5-9c79-b1c700f738eb
        property: password
