---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secretName alertmanager
spec:
  refreshInterval: 5m
  target:
    name: *secretName
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
          route:
            group_by: ["alertname", "job"]
            group_interval: 10m
            group_wait: 1m
            receiver: discord
            repeat_interval: 12h
            routes:
              - receiver: discord
                group_interval: 5m
                group_wait: 0s
                matchers:
                  - alertname =~ "Watchdog"
                repeat_interval: 5m
              - receiver: "null"
                matchers:
                  - alertname =~ "InfoInhibitor"
              - receiver: discord
                continue: true
                matchers:
                  - severity = "critical"
          inhibit_rules:
            - equal: ["alertname", "namespace"]
              source_matchers:
                - severity = "critical"
              target_matchers:
                - severity = "warning"
          receivers:
            - name: discord
              webhook_configs:
                - send_resolved: true
                  url: "{{ .address }}"
            - name: "null"
  data:
    - secretKey: address
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d328da7a-35ec-4d38-9a5f-b1ca006db221
        property: address
