---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Flux-Kustomizations
  - ./helm-release.yaml
  - ./cloudflare

configMapGenerator:
  - name: cert-manager-helm-values
    files:
      - values.yaml=./helm-values.yaml

configurations:
  - ./kustomize-config.yaml
