apiVersion: v1
kind: Service
metadata:
  name: &app chrome
  labels:
    app: *app
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.2.50
spec:
  type: LoadBalancer
  selector:
    app: *app
  ports:
    - port: 6901
      targetPort: 6901
      name: web
    - port: 9222
      targetPort: 9222
      name: rmdebug
