---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-lab-private
spec:
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-lab-private
  wait: false
  interval: 1m
  retryInterval: 1m
  timeout: 1m
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
