---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secretName grafana-admin
spec:
  target:
    name: *secretName
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        admin-user: |-
          {{ .username }}
        admin-password: |-
          {{ .password }}
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 37c82b42-650a-4921-bac7-b1cf012382bf
        property: password
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 37c82b42-650a-4921-bac7-b1cf012382bf
        property: username
