apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: mariadb
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "mariadb-data"

      containers:
        - name: "mariadb"
          image: mariadb:11
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306

          envFrom:
            - secretRef:
                name: mariadb

          env:
            - name: TZ
              value: Europe/Warsaw

          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql

          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 10
