apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.2.3
spec:
  type: LoadBalancer
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
      name: mariadb
