apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana-agent
spec:
  interval: 1h
  chart:
    spec:
      version: 0.4.1
      chart: grafana-agent
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
      interval: 1h

  install:
    crds: Create
  upgrade:
    crds: CreateReplace
