apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.2.5
spec:
  type: LoadBalancer
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
