apiVersion: v1
kind: ConfigMap
metadata:
    name: cloudflared-config
data:
    config.yaml: |
        tunnel: rpi
        credentials-file: /etc/cloudflared/creds/credentials.json
        metrics: 0.0.0.0:2000
        no-autoupdate: true
        ingress:
          - hostname: echo.psalkowski.pl
            service: http://echoserver.echoserver
          - hostname: n8n.psalkowski.pl
            service: http://n8n.n8n
          - service: http_status:404
