# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-credentials
spec:
  target:
    name: cloudflared-credentials
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        credentials.json: {{ .credentials | quote }}
  data:
    - secretKey: credentials
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 39fb78d6-abd3-4e4a-8651-b153010b079d
        property: "credentials"
