---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Flux-Kustomizations
  - ./cloudflared-config.sops.yaml
  - ./cloudflared-credentials.sops.yaml
  - ./daemonset.yaml
