---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: &app external-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-crds
  targetNamespace: vault
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/home/vault/external-secrets/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: git-ops
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-crs
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-crds
  interval: 10m
  path: ./clusters/home/vault/external-secrets/crs
  prune: true
  sourceRef:
    kind: GitRepository
    name: git-ops
