---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: flux-system
spec:
  releaseName: *app
  targetNamespace: home-assistant
  interval: 10m

  chart:
    spec:
      chart: home-assistant
      version: 0.2.65
      sourceRef:
        kind: HelmRepository
        name: pajikos
        namespace: flux-system

  values:
    persistence:
      enabled: true
      storageClass: "longhorn"
      accessMode: ReadWriteOnce
      size: 5Gi

    hostNetwork: false

    configuration:
      enabled: true
      forceInit: true

    ingress:
      enabled: true
      className: "nginx"
      annotations:
        kubernetes.io/ingress.class: nginx
        external-dns.alpha.kubernetes.io/target: "psalkowski.pl"
        external-dns.alpha.kubernetes.io/hostname: &host "ha.psalkowski.pl"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      hosts:
        - host: *host
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: home-assistant-tls
          hosts:
            - *host

    addons:
      codeserver:
        enabled: true

    service:
      type: ClusterIP
      port: 8123
