# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secretName nexus-adminsecret
spec:
  target:
    name: *secretName
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        nexus-admin-password: |-
          {{ .password }}

  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 4e2ccf95-0b82-4e1e-91d7-b1c800d4b3c5
        property: password

    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 4e2ccf95-0b82-4e1e-91d7-b1c800d4b3c5
        property: username
