# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secretName nexus-dbsecret
spec:
  refreshInterval: 5m
  target:
    name: *secretName
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        db-user: |-
          {{ .username }}
        db-password: |-
          {{ .password }}
        db-host: postgres.database

  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: df0ca74f-7e9c-4b72-b999-b1c701015710
        property: password
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: df0ca74f-7e9c-4b72-b999-b1c701015710
        property: username
