apiVersion: v1
kind: Secret
metadata:
    name: vault-token-global
stringData:
    token: ENC[AES256_GCM,data:AjTMMQounTAF+Wg=,iv:Y4cw4vLKUsT7JrWVD4+ZO4xcg6DGrYA6OSeIz2H/nGc=,tag:NfxsFutR8d0CkiM9i53lTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-15T13:20:31Z"
    mac: ENC[AES256_GCM,data:rJ8RuDKj5zxbMxDX7skJZP+PBBMNG1mn+PHg2AVpnFqaDi7rw+ponH2RmHMs/pZm4qpAOwwudS1gXksFJWJm5veSj6VHYO3V/aIsY8WuemzlUqr14DoXHQ7fNeyCVhv+6p35dmtWeOXU+Xwc0WKlR9ITD8xvFhBxZoKcnIteEMM=,iv:1SvQrleRtJ2vMkS/YPBeZ+KCXnOjFeL6hybwRgel7yE=,tag:NY/vvX97giAHu2ZhB8jqrQ==,type:str]
    pgp:
        - created_at: "2024-04-15T13:20:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+5DLFyTQx3jAQ//frLTcj92HB+7AXblc8cTVU3CEcIm2ErsbGd3DMSQslMI
            iAGirNMsAVE9V44leMP893G+kpf4PU2Jaz43FRoy0pGvIoGpzmSCoQ8WoV9gJE3q
            d9e3aIIae31fp37UrD4A/vt1qeBcEbuXJvQtlE+LPorVlujtNUJY69Uqsi4nE4n7
            v2ukznTcBwWRcLY22LXU3P89B/Z+Gs4TsRZGNCsJBSVJkyR+yyaMWi6EoHoEy/l3
            kPv9iaENUCuGBFrQ975CqQqkVyYJfge7Qy6I5ltH8EHv1qkVszdShj3UK0UNrlhB
            +8+37kujlD5haVZDw1XQk6fUlSkIxdb9AGaxvfKfZ85TsH8HxrcPFPmqauPjBJMh
            g2KHWFMwot66n4rM/02bF0Yp+aBroxiuf/Yj4YtsTws/c9KrENiu9t2tAiPRWh+7
            FrX2q6kwBR4rlnKHFQOvyZkxZ8DQaDl7EW9iw4WzHho1FAUDlt/0mofNoWAmBoiA
            irMLgaXF3wLJmMwZ9G7FCYwvvNjHCC0sJioBSDmRJ4TemI9Iq6CZwoMW3fCtOTAP
            7T0CTaPQXCbLJEURHEQn77KDIAf7jZhSufqwi0M1Vx+GWND2AWYGZt3y5EvXstwP
            lvEhcYrQTUoOd7OP02Hah40/GS/71jIRhzG4jwBC/fHUB3R6/vz1/aR1uPTnL5TU
            ZgEJAhB3G8YG0Q8ncD0Q7fxedPgOSmxw9BYvqB0viJ6VXQvGfm80gOiJLu61vNwy
            5gJOGpitBEBM60gCnUnq9gyHUodSi7ypIENyBbBppUdimTxcdqf+zGZxbZ9zFHXw
            DvCbWjXgBw==
            =nUUE
            -----END PGP MESSAGE-----
          fp: 0AAF5FE46B52389FC9592F437F372F40F521140D
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
