---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Flux-Kustomizations
  - cloudflare.sops-secret.yaml
  - dns01-sandbox.cluster-issuer.yaml
  - dns01-production.cluster-issuer.yaml


