---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: 8gears
  namespace: flux-system
spec:
  type: oci
  interval: 2h
  url: oci://8gears.container-registry.com/library
