---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jetstack.yaml
  - external-dns.yaml
  - ingress-nginx.yaml
  - metallb.yaml
  - external-secrets.yaml
  - 8gears.yaml
  - pajikos.yaml
  - sonatype.yaml
