---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app monitoring-configs
  namespace: flux-system
spec:
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/home/monitoring/configs/app
  prune: true
  dependsOn:
    - name: loki
    - name: kube-prometheus-stack
  sourceRef:
    kind: GitRepository
    name: git-ops
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
