---
# yaml-language-server: $schema=https://raw.githubusercontent.com/kubernetes-sigs/external-dns/master/charts/external-dns/values.schema.json
provider: cloudflare
sources:
  - ingress
domainFilters:
  - psalkowski.pl
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        key: CF_API_TOKEN
        name: external-dns-cloudflare
