# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secretName aws-secret
spec:
  refreshInterval: 5m
  target:
    name: *secretName
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: |-
          {{ .AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: |-
          {{ .AWS_SECRET_ACCESS_KEY }}
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8e0f6bc5-5073-43f5-bb67-b18d010423ab
        property: access_key
    - secretKey: AWS_SECRET_ACCESS_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8e0f6bc5-5073-43f5-bb67-b18d010423ab
        property: secret_key
