---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m

  chart:
    spec:
      chart: longhorn
      version: 1.6.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: storage

  install:
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  dependsOn:
    - name: cert-manager
      namespace: home-system
    - name: ingress-nginx
      namespace: home-system
    - name: external-dns
      namespace: home-system

  values:
    defaultSettings:
      defaultDataPath: /mnt/cluster/cluster-storage

    defaultNodeSelector:
      enable: true
      selector: "persistent"

    ingress:
      enabled: true
      ingressClassName: nginx
      host: longhorn.psalkowski.pl
      tls: true
      tlsSecret: longhorn.psalkowski.pl-tls

      annotations:
        cert-manager.io/issuer: "letsencrypt-production"
        external-dns.alpha.kubernetes.io/hostname: "longhorn.psalkowski.pl"
