apiVersion: v1
kind: Namespace
metadata:
  name: n8n
  labels:
    app.kubernetes.io/component: apps
    pod-security.kubernetes.io/enforce: privileged
    kustomize.toolkit.fluxcd.io/prune: disabled
